[workspace]                                                                                                              
members = [                                                                                                              
    "rlp",
    "rlp-compress",
    "rlp-derive"
]
